using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;


public class PlayerController : MonoBehaviour {
    Vector3 direction;
    public float speed = 0.5f;
#if tmp
    public GameObject bullet;
#endif
    AudioSource aus;
    // Start is called before the first frame update
    void Start() {
        aus = GetComponent<AudioSource>();
    }

    // Update is called once per frame
    void Update() {
        gameObject.transform.position += new Vector3(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical"), 0)*speed;
        if (Input.GetButton("Fire1")) gameObject.BroadcastMessage("Fire");
    }
}
